apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "charts-nodejs.selectorLabels" . | nindent 6 }}
  template:
    metadata: 
      labels:
        {{- include "charts-nodejs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              value: {{ .Values.env.pg_user }}
            - name: DB_HOST
              value: {{ .Values.env.db_host }}
            - name: DB_NAME
              value: {{ .Values.env.db_name }}
            - name: DB_PASSWORD
              value: {{ .Values.env.pg_pass }}  


            
    